/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Form to subscribe to notifications when a Selector has been triggered by new Events. Use this schema to create a subscription request and POST it back to SUBSCRIBE_URI endpoint.
 */
export type SelectorSubscriptionForm =
  | {
      after?: After
      entities: Entities
      events?: DataQuery
      meta?: MetaQuery
    }
  | {
      after?: After
      entities?: Entities
      events: DataQuery
      meta?: MetaQuery
    }
  | {
      after?: After
      entities?: Entities
      events?: DataQuery
      meta: MetaQuery
    }
/**
 * Select events that occur after this event ID.
 */
export type After = string

/**
 * The entity name is the key, value is an entity key, or array of keys.
 */
export interface Entities {
  /**
   * @minItems 1
   *
   * This interface was referenced by `Entities`'s JSON-Schema definition
   * via the `patternProperty` "^[^\x00-\x1F\x80-\x9F]{1,80}$".
   */
  [k: string]: [string, ...string[]]
}
/**
 * Filter by event data values. Keys are event names, and the values are SQL JSONPath query objects.
 */
export interface DataQuery {
  [k: string]: JsonpathQuery
}
/**
 * JSONPath query to filter JSON objects.
 */
export interface JsonpathQuery {
  /**
   * A JSONPath query statement. Can include named variables, like '$age' or '$orderNumber'.
   */
  query: string
  /**
   * If the query contains named variables, they are stored in this object. The object keys are the variable names, without the preceding '$', like 'age' and 'orderNumber'.
   */
  vars?: {
    [k: string]: unknown
  }
}
/**
 * SQL JSONPath filter on the event's meta object.
 */
export interface MetaQuery {
  /**
   * A JSONPath query statement. Can include named variables, like '$age' or '$orderNumber'.
   */
  query: string
  /**
   * If the query contains named variables, they are stored in this object. The object keys are the variable names, without the preceding '$', like 'age' and 'orderNumber'.
   */
  vars?: {
    [k: string]: unknown
  }
}
