/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NameString = string

/**
 * Form to register an entity event. Create a JSON object using this schema and POST it back to REGISTER_URI endpoint.
 */
export interface RegisterEntityEventForm {
  event: NameString
  /**
   * @minItems 1
   */
  entities: [NameString, ...NameString[]]
}
