/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SelectorHeaders {
  /**
   * Do not make this required, it blocks the 401 status code, which is more helpful than 400.
   */
  authorization?: string
  "if-none-match"?: string
  "accept-encoding"?: string
  prefer?: "return=representation" | "return=minimal"
}
